package com.example.library_management_system.data_models.BookDataModel.GetAllBooks

import com.example.library_management_system.data_models.BookDataModel.GetBookById.getbookbyid_response

class getallbook_response : ArrayList<getbookbyid_response>()